name: wise_players
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter_riverpod: ^3.2.0
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  carousel_slider: ^5.1.1
  device_info_plus: ^12.3.0
  crypto: ^3.0.7
  flutter_localizations:


    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.11
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/wplogo.png"



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/




flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
  # flutter pub run intl_utils:generate
